### ISSUE TITLE
Compatiblility with VTK>8.1.2 and Python 3.8

### ISSUE THREAD

**Issue by tdowrick** [SciKit-Surgery/scikit-surgeryvtk#165]
We currently specify VTK<=8.1.2 in requirements.txt, but this version doesn't exist for Python 3.8 (only 9.0.0 onwards).

I remember there was previously some problem for us with using vtk 9.0.0, but don't remember exactly what it was. We will need to fix this at some point, otherwise we won't be able to support Python 3.8+.

**Comment by tdowrick** [comment]
So I seem to have found a combination of PySide2 and VTK that works for Python 3.6, 3.7 and 3.8, with all CI passing (https://github.com/UCL/scikit-surgeryvtk/actions/runs/531398630).

I think it is worth manually checking that this hasn't broken anything in other scikit-surgery libraries before we merge/tag, so I will make a start on that.

@MattClarkson @thompson318 @mianasbat

**Comment by tdowrick** [comment]
Also any objections to tagging this as v1.0 when it is working?

**Comment by thompson318** [comment]
I'm on Ubuntu 20.04.2. I can't get vtk > 9.0.0 working. I've tried Python 3.6.10, 3.7.7, and 3.8.3. They all hang when we call self.Initialize() in vtk_overlay_window.py. vtk 8.1.2 seems fine.

**Comment by tdowrick** [comment]
GitHub Actions CI is using Ubuntu 20.04.2 and seems to be fine (https://github.com/UCL/scikit-surgeryvtk/actions)

What VTK version are you trying? We have <= 9.0.1 in requirements.txt.

**Comment by thompson318** [comment]
vtk-9.0.1 not working. vtk-8.1.2 working. Thus far I've managed to work out that setting up Xvfb and DISPLAY will get tox to run OK locally (previously this was not necessary)

**Comment by thompson318** [comment]
By setting xvfb and display properly I can get tox to run consistently. I'm still having some issues running applications that use vtk_overlay_window. For example if I try running snappysonic, I can run it twice OK, then on the third run it hangs at self.Initialize() as above. If I then start a new terminal it runs OK again. (very weird)

**Comment by mxochicale** [comment]
Closing this one in favour of #187 which pass remote unit tests with the latest oss in python 3.8, 3.9, 3.10, and 3.11 using "vtk>=9.2.5"
