### ISSUE TITLE
Remove version specifiers on Pyside2 and VTK

### ISSUE THREAD

**Issue by MattClarkson** [SciKit-Surgery/scikit-surgeryvtk#186]

**Comment by mxochicale** [comment]
I think we need to add version specifiers to packages, helping us to have more stability of coming and future releases. I think we can close this one and perhaps remove stale branch https://github.com/SciKit-Surgery/scikit-surgeryvtk/tree/186-pyside-vtk-versions

**Comment by thompson318** [comment]
We should discuss at next SNAPPY meeting. I think I disagree as by adding version specifiers we could make the software harder to maintain in the future and harder for other people to use in their applications. 
Are you aware of any recommended guidance on this from an RSE point of view? Could ask for opinions within ARC?

**Comment by thompson318** [comment]
Duplicate #187
