### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by mxochicale** [SciKit-Surgery/scikit-surgeryvtk#197]
I am having issues when using different versions of scikit-surgeryvtk (e.g., v1.1.0 and v1.0.6: https://github.com/SciKit-Surgery/scikit-surgerytutorial01/issues/34). Version changes are not obvious to me unless you look the commit [logs](https://github.com/SciKit-Surgery/scikit-surgeryvtk/commit/d0c18df7be5ac9bdd9082837bb9939b5f8814b08). I think it will be helpful to add releases notes to this one and perhaps to other SciKit-Surgery libs  (e.g., Highlights, Backwards Incompatible Change, New Features, Improvements, Performance, Documentation, etc https://github.com/pytorch/pytorch/releases)

Thanks

**Comment by thompson318** [comment]
I agree that would be good practice. We usually put a short message for each tag, but we could do better.

**Comment by mxochicale** [comment]
It seems that `pylint` might be a example on creating release notes, containing: 
* Summary -- Release highlights
* What's new in Pylint 2.16.0? Changes requiring user actions
* New Features
* New Checks
* Extensions
* False Positives Fixed
* False Negatives Fixed
* Other Bug Fixes
* Other Changes
* Internal Changes
* Contributors

See more:  https://github.com/PyCQA/pylint/releases/tag/v2.16.0

**Comment by mxochicale** [comment]
Another good example of release notes is the log from pytorch:
https://github.com/pytorch/pytorch/releases
