### ISSUE TITLE
Stale branches

### ISSUE THREAD

**Issue by mxochicale** [SciKit-Surgery/scikit-surgeryvtk#201]
https://github.com/SciKit-Surgery/scikit-surgeryvtk/branches has 2 out of 36 activate branches https://github.com/SciKit-Surgery/scikit-surgeryvtk/branches which seems to be a bad software engineering practice.

I would suggest to archive branches in PRs as it is shown here https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/deleting-and-restoring-branches-in-a-pull-request or  https://medium.com/@vbabak/how-to-deal-with-stale-branches-on-the-github-b49727480872

For future work, we might like to prioritise branches and raise PRs and merge to main branch to avoid having lots of stale branches.

Thanks

**Comment by thompson318** [comment]
I agree. We just need to tidy these up and remember to delete when we merge.

**Comment by mxochicale** [comment]
Hi @thompson318 and @MattClarkson 

Would you like to [archive](https://medium.com/@vbabak/how-to-deal-with-stale-branches-on-the-github-b49727480872) the following stale branches?: 
* [ ] [56-prototyping-touchscreen-stuf](https://github.com/SciKit-Surgery/scikit-surgeryvtk/tree/56-prototyping-touchscreen-stuf) Updated 4 years ago by [MattClarkson](https://github.com/MattClarkson)
* [ ] [70-stereo-interlace](https://github.com/SciKit-Surgery/scikit-surgeryvtk/tree/70-stereo-interlace) Updated 4 years ago by [MattClarkson](https://github.com/MattClarkson)
* [ ] [91-suppress-empty-transform-error](https://github.com/SciKit-Surgery/scikit-surgeryvtk/tree/91-suppress-empty-transform-error) Updated 3 years ago by [thompson318](https://github.com/thompson318)
* [ ] [14-consistent-name-surface-model](https://github.com/SciKit-Surgery/scikit-surgeryvtk/tree/14-consistent-name-surface-model) Updated 3 years ago by [MattClarkson](https://github.com/MattClarkson)
* [ ] [176-match-sl-sppa](https://github.com/SciKit-Surgery/scikit-surgeryvtk/tree/176-match-sl-sppa) Updated 2 years ago by [MattClarkson](https://github.com/MattClarkson)
* [ ] [185-opencv-headless](https://github.com/SciKit-Surgery/scikit-surgeryvtk/tree/185-opencv-headless) Updated last year by [MattClarkson](https://github.com/MattClarkson)
* [ ] [186-pyside-vtk-versions](https://github.com/SciKit-Surgery/scikit-surgeryvtk/tree/186-pyside-vtk-versions) Updated 10 months ago by [MattClarkson](https://github.com/MattClarkson)

**Comment by thompson318** [comment]
Either archive or delete. I've already deleted all the ones I was sure about.

**Comment by mxochicale** [comment]
Stale branch were archived following the [PR workflow](https://medium.com/@vbabak/how-to-deal-with-stale-branches-on-the-github-b49727480872).
