### ISSUE TITLE
Shall we support VTK 9.3.0? 

### ISSUE THREAD

**Issue by mxochicale** [SciKit-Surgery/scikit-surgeryvtk#223]
Shall we support https://gitlab.kitware.com/vtk/vtk/-/tags/v9.3.0? (to be expanded with pros and cons, and bring to discussions potential solutions)

**Comment by thompson318** [comment]
Had a look at the history of vtk>=9.2.6. Lots of testing and iteration during https://github.com/SciKit-Surgery/scikit-surgeryvtk/issues/216, so we need to be careful with changing the vtk version.

**Comment by MattClarkson** [comment]
For #222 - runners are picking up 9.3.0 anyway, which is where some unit tests fail, as some API which was marked deprecated in 9.2.6 was removed in 9.3.0. It may well be put back in according to their discussions, but we can also just update our code in scikit-surgeryvtk. 

Done this as part of #222.
