### ISSUE TITLE
Use VTKOverlayWindow as a widget in QtCreator

### ISSUE THREAD

**Issue by thompson318** [SciKit-Surgery/scikit-surgeryvtk#46]
In GitLab by @ThomasDowrick on Feb 8, 2019, 12:12

I was chatting with Eddie and he thinks this would be useful. I assume it is possible, but not sure how at the moment.

**Comment by mxochicale** [comment]
This seems to be resolved in master and the coming merge of #187 
Feel free to re-open it if this is required.
